export type Denomination = { label: string; type: "coin" | "note" };
export type CurrencyOption = { name: string; denominations: Denomination[] };

export const OTHER_CURRENCY = "Other (type your own)";

export const CURRENCIES: CurrencyOption[] = [
  {
    name: "Euro",
    denominations: [
      { label: "1 cent", type: "coin" },
      { label: "2 cent", type: "coin" },
      { label: "5 cent", type: "coin" },
      { label: "10 cent", type: "coin" },
      { label: "20 cent", type: "coin" },
      { label: "50 cent", type: "coin" },
      { label: "1 euro", type: "coin" },
      { label: "2 euro", type: "coin" },
      { label: "5 euro", type: "note" },
      { label: "10 euro", type: "note" },
      { label: "20 euro", type: "note" },
      { label: "50 euro", type: "note" },
      { label: "100 euro", type: "note" },
      { label: "200 euro", type: "note" },
      { label: "500 euro (legacy)", type: "note" },
    ],
  },
  {
    name: "US Dollar",
    denominations: [
      { label: "1 cent (penny)", type: "coin" },
      { label: "5 cent (nickel)", type: "coin" },
      { label: "10 cent (dime)", type: "coin" },
      { label: "25 cent (quarter)", type: "coin" },
      { label: "50 cent (half dollar)", type: "coin" },
      { label: "$1 coin", type: "coin" },
      { label: "$1 note", type: "note" },
      { label: "$2 note", type: "note" },
      { label: "$5 note", type: "note" },
      { label: "$10 note", type: "note" },
      { label: "$20 note", type: "note" },
      { label: "$50 note", type: "note" },
      { label: "$100 note", type: "note" },
    ],
  },
  {
    name: "British Pound Sterling",
    denominations: [
      { label: "1 penny", type: "coin" },
      { label: "2 pence", type: "coin" },
      { label: "5 pence", type: "coin" },
      { label: "10 pence", type: "coin" },
      { label: "20 pence", type: "coin" },
      { label: "50 pence", type: "coin" },
      { label: "£1 coin", type: "coin" },
      { label: "£2 coin", type: "coin" },
      { label: "£5 note", type: "note" },
      { label: "£10 note", type: "note" },
      { label: "£20 note", type: "note" },
      { label: "£50 note", type: "note" },
    ],
  },
  {
    name: "Japanese Yen",
    denominations: [
      { label: "¥1", type: "coin" },
      { label: "¥5", type: "coin" },
      { label: "¥10", type: "coin" },
      { label: "¥50", type: "coin" },
      { label: "¥100", type: "coin" },
      { label: "¥500", type: "coin" },
      { label: "¥1000 note", type: "note" },
      { label: "¥2000 note", type: "note" },
      { label: "¥5000 note", type: "note" },
      { label: "¥10000 note", type: "note" },
    ],
  },
  {
    name: "Swiss Franc",
    denominations: [
      { label: "5 rappen", type: "coin" },
      { label: "10 rappen", type: "coin" },
      { label: "20 rappen", type: "coin" },
      { label: "1/2 franc", type: "coin" },
      { label: "1 franc", type: "coin" },
      { label: "2 francs", type: "coin" },
      { label: "5 francs", type: "coin" },
      { label: "10 francs note", type: "note" },
      { label: "20 francs note", type: "note" },
      { label: "50 francs note", type: "note" },
      { label: "100 francs note", type: "note" },
      { label: "200 francs note", type: "note" },
      { label: "1000 francs note", type: "note" },
    ],
  },
  {
    name: "Canadian Dollar",
    denominations: [
      { label: "5 cent", type: "coin" },
      { label: "10 cent", type: "coin" },
      { label: "25 cent", type: "coin" },
      { label: "50 cent", type: "coin" },
      { label: "$1 coin (loonie)", type: "coin" },
      { label: "$2 coin (toonie)", type: "coin" },
      { label: "$5 note", type: "note" },
      { label: "$10 note", type: "note" },
      { label: "$20 note", type: "note" },
      { label: "$50 note", type: "note" },
      { label: "$100 note", type: "note" },
    ],
  },
  {
    name: "Australian Dollar",
    denominations: [
      { label: "5 cent", type: "coin" },
      { label: "10 cent", type: "coin" },
      { label: "20 cent", type: "coin" },
      { label: "50 cent", type: "coin" },
      { label: "$1 coin", type: "coin" },
      { label: "$2 coin", type: "coin" },
      { label: "$5 note", type: "note" },
      { label: "$10 note", type: "note" },
      { label: "$20 note", type: "note" },
      { label: "$50 note", type: "note" },
      { label: "$100 note", type: "note" },
    ],
  },
];
